# Generated by Django 3.2.7 on 2021-10-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('rutadm', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombreadm', models.CharField(max_length=300)),
                ('apellidoadm', models.CharField(max_length=300)),
                ('edadadm', models.IntegerField()),
                ('emailadm', models.CharField(max_length=300)),
                ('telefonoadm', models.IntegerField()),
            ],
            options={
                'db_table': 'administrador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('codename', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(blank=True, max_length=128, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('email', models.CharField(blank=True, max_length=254, null=True)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id_checkout', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('listacheckout', models.CharField(max_length=300)),
                ('multas', models.CharField(blank=True, max_length=300, null=True)),
                ('reparaciones', models.CharField(blank=True, max_length=300, null=True)),
                ('checkin_id_checkin', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'checkout',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rut', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=300)),
                ('apellidos', models.CharField(max_length=300)),
                ('edad', models.IntegerField()),
                ('correo', models.CharField(max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_depto', models.CharField(db_column='IDdepto', max_length=300, primary_key=True, serialize=False)),
                ('m2', models.CharField(max_length=300)),
                ('piezas', models.IntegerField()),
                ('banos', models.IntegerField()),
                ('terraza', models.CharField(max_length=100)),
                ('direcciondepto', models.CharField(max_length=300)),
                ('imagenes', models.BinaryField()),
            ],
            options={
                'db_table': 'departamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccioncompleta', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=300)),
                ('comuna', models.CharField(max_length=300)),
                ('depto', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(blank=True, max_length=200, null=True)),
                ('action_flag', models.IntegerField()),
                ('change_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField(blank=True, null=True)),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('rut_f', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('nombref', models.CharField(max_length=300)),
                ('apellidof', models.CharField(max_length=300)),
                ('edadf', models.IntegerField()),
                ('correof', models.CharField(max_length=300)),
                ('telefono', models.IntegerField()),
            ],
            options={
                'db_table': 'funcionario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Mantenciones',
            fields=[
                ('tipo_mantencion', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('fecha', models.CharField(max_length=300)),
                ('hora', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'mantenciones',
                'managed': False,
            },
        ),
    ]
