# Generated by Django 3.2.7 on 2021-11-20 21:00

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20211029_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inv', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('cocina', models.CharField(max_length=200)),
                ('muebles', models.CharField(max_length=200)),
                ('banoinv', models.CharField(max_length=200)),
                ('camas', models.CharField(max_length=200)),
                ('extras', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(default=accounts.models.random_string, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('desde', models.CharField(max_length=200)),
                ('vehiculo', models.CharField(blank=True, max_length=200, null=True)),
                ('horario', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'transporte',
                'managed': False,
            },
        ),
    ]
